# Mask Detection Model Config

data_paths:
  train_root_dir: ..\assets\data\mask\train\
  test_root_dir: ..\assets\data\mask\eval\
  training_data_file: train.csv
  test_data_file: test_data.csv

save_paths:
  root_dir: ../assets/results/
  checkpoints_dir: checkpoint/
  tensorboard_dir: tensorboard/
  yaml_dir: yaml_log/

hyperparameters:
  seed: 327459
  epochs: 40

  dataloader:
    target_fold: -1   # -1인 경우 all
    args:
      seed: 327459
      kfold_n_splits: 5
      image_side_length: 384
      cross_validation: False
      train_loader_args:
        batch_size: 64
      valid_loader_args:
        batch_size: 64

  model:
    name: Efficientnet
    args:
      num_classes: 3
      pretrained_model_name: efficientnet-b5
      backbone_freeze: True
  loss:
    name: FocalLoss
    args:
      weight: null
      gamma: 2
      reduction: mean

  optimizer:
    name: AdamW
    args:
      lr: 0.0001
      weight_decay: 0.01

  scheduler:
    name: CosineAnnealingLR
    args:
      T_max: 50
      eta_min: 0

trainee_name: MaskEff
trainee_type: MaskModelTrainee
