# Trip Advisor DST Model Config
trainee_name: TripDST
trainee_type: DSTTrainee

data_paths:
  train_root_dir: .\assets\data\trip\wos-v1\
  test_root_dir: .\assets\data\trip\wos-v1\
  training_data_file: wos-v1_train.json
  test_data_file: wos-v1_dev.json
  ontology_data_file: ontology.json

save_paths:
  root_dir: ../assets/results/
  checkpoints_dir: checkpoint/
  tensorboard_dir: tensorboard/
  yaml_dir: yaml_log/

hyperparameters:
  seed: 327459
  epochs: 40
  skf:
    args:
      split_k: 5
      seed: 327459
      target_fold: 2
  tokenizer_pretrained_model_name_or_path: "dsksd/bert-ko-small-minimal"
  preprocessing:
    args: null
  dataloader:
    args: null
  model:
    name: Efficientnet
    args: null
  loss:
    name: Efficientnet
    args: null
  optimizer:
    name: Efficientnet
    args: null
  scheduler:
    name: Efficientnet
    args: null
